name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.3
      id: go

    - name: Code checkout
      uses: actions/checkout@v1

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        skip-go-installation: true

    - name: Code sanity
      run: |
        go vet ./...
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

    - name: Run tests
      run: |
        go test -v ./...

    - name: Build
      run: |
        go build -v .