name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.22
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
      id: go

    - name: Code checkout
      uses: actions/checkout@v4

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6

    - name: Code vetting
      shell: bash
      run: |
        go vet ./...

    - name: code format check
      shell: bash
      run: |
        if [ "$(gofmt -s -l .)" != "" ]; then exit 1; fi

    - name: Run tests
      run: |
        go test -v ./...

    - name: Build
      run: |
        go build -v .